### ISSUE TITLE
Launch Successfully,  But Fail After input Url in Browser

### ISSUE THREAD

**Issue by zddllc** [beidongjiedeguang/openai-forward#15]
成功启动，没有问题，但是在浏览器里访问 http://0.0.0.0:9999/ 或者 http://0.0.0.0:9999/v1/chat/completions
就是出现这个错误，请问是什么情况，大神求助！应该不会仅局限在有公网ip的机器吧。

Traceback (most recent call last):

File "/home/user/anaconda3/envs/py39/bin/openai_forward", line 8, in
sys.exit(main())
│ │ └ <function main at 0x7f8353162a60>
│ └
└ <module 'sys' (built-in)>
File "/home/user/anaconda3/envs/py39/lib/python3.9/site-packages/openai_forward/main.py", line 21, in main
fire.Fire(Cli)
│ │ └ <class 'openai_forward.main.Cli'>
│ └ <function Fire at 0x7f8352fb25e0>
└ <module 'fire' from '/home/user/anaconda3/envs/py39/lib/python3.9/site-packages/fire/init.py'>
File "/home/user/anaconda3/envs/py39/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
component_trace = _Fire(component, args, parsed_flag_args, context, name)
│ │ │ │ │ └ 'openai_forward'
│ │ │ │ └ {}
│ │ │ └ Namespace(verbose=False, interactive=False, separator='-', completion=None, help=False, trace=False)
│ │ └ ['run', '--port=9999', '--workers=1']
│ └ <class 'openai_forward.main.Cli'>
└ <function _Fire at 0x7f8352814a60>
File "/home/user/anaconda3/envs/py39/lib/python3.9/site-packages/fire/core.py", line 475, in _Fire
component, remaining_args = _CallAndUpdateTrace(
│ └ <function _CallAndUpdateTrace at 0x7f8352814b80>
└ <function Cli.run at 0x7f8352fb2550>
File "/home/user/anaconda3/envs/py39/lib/python3.9/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
component = fn(*varargs, **kwargs)
│ │ └ {}
│ └ [9999, 1]
└ <function Cli.run at 0x7f8352fb2550>
File "/home/user/anaconda3/envs/py39/lib/python3.9/site-packages/openai_forward/main.py", line 9, in run
uvicorn.run(
│ └ <function run at 0x7f83524bac10>
└ <module 'uvicorn' from '/home/user/anaconda3/envs/py39/lib/python3.9/site-packages/uvicorn/init.py'>
File "/home/user/anaconda3/envs/py39/lib/python3.9/site-packages/uvicorn/main.py", line 578, in run
server.run()
│ └ <function Server.run at 0x7f83524ba670>
└ <uvicorn.server.Server object at 0x7f83524159a0>
File "/home/user/anaconda3/envs/py39/lib/python3.9/site-packages/uvicorn/server.py", line 61, in run
return asyncio.run(self.serve(sockets=sockets))
│ │ │ │ └ None
│ │ │ └ <function Server.serve at 0x7f83524ba700>
│ │ └ <uvicorn.server.Server object at 0x7f83524159a0>
│ └ <function run at 0x7f835292adc0>
└ <module 'asyncio' from '/home/user/anaconda3/envs/py39/lib/python3.9/asyncio/init.py'>
File "/home/user/anaconda3/envs/py39/lib/python3.9/asyncio/runners.py", line 44, in run
return loop.run_until_complete(main)
│ │ └ <coroutine object Server.serve at 0x7f8352481b40>
│ └ <function BaseEventLoop.run_until_complete at 0x7f835292c820>
└ <_UnixSelectorEventLoop running=True closed=False debug=False>
File "/home/user/anaconda3/envs/py39/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
self.run_forever()
│ └ <function BaseEventLoop.run_forever at 0x7f835292c790>
└ <_UnixSelectorEventLoop running=True closed=False debug=False>
File "/home/user/anaconda3/envs/py39/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
self._run_once()
│ └ <function BaseEventLoop._run_once at 0x7f835292e310>
└ <_UnixSelectorEventLoop running=True closed=False debug=False>
File "/home/user/anaconda3/envs/py39/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
handle._run()
│ └ <function Handle._run at 0x7f83529f5790>
└ <Handle <TaskStepMethWrapper object at 0x7f83507da130>()>
File "/home/user/anaconda3/envs/py39/lib/python3.9/asyncio/events.py", line 80, in _run
self._context.run(self._callback, *self._args)
│ │ │ │ │ └ <member '_args' of 'Handle' objects>
│ │ │ │ └ <Handle <TaskStepMethWrapper object at 0x7f83507da130>()>
│ │ │ └ <member '_callback' of 'Handle' objects>
│ │ └ <Handle <TaskStepMethWrapper object at 0x7f83507da130>()>
│ └ <member '_context' of 'Handle' objects>
└ <Handle <TaskStepMethWrapper object at 0x7f83507da130>()>

**Comment by beidongjiedeguang** [comment]
这个服务只是用于转发 openai api官方的路由接口，运行此服务的服务器本身需要能够正常访问  https://api.openai.com ;  
你可以通过修改`环境变量`（或`.env`文件）中的 `OPENAI_BASE_URL=https://caloi.top/openai` 来判断是否是网络原因导致的错误。

**Comment by zddllc** [comment]
> 这个服务只是用于转发 openai api官方的路由接口，运行此服务的服务器本身需要能够正常访问 https://api.openai.com ; 你可以通过修改`环境变量`（或`.env`文件）中的 `OPENAI_BASE_URL=https://caloi.top/openai` 来判断是否是网络原因导致的错误。

我这个机器是在北美的，肯定可以访问。我明天修改下再试试什么情况。我在一个有公网ip的机器上已经用起来了，确实很好用。赞!
