### ISSUE TITLE
openai_forward不支持whisper功能？

### ISSUE THREAD

**Issue by tangyiyong** [beidongjiedeguang/openai-forward#49]
python： 3.10.9
openai_forward: 0.2.4
命令行：nohup openai_forward run --port=36001 > openai_forward.log 2>&1 &

示例代码：
curl https://api.openai.com/v1/audio/translations \
  -H "Authorization: Bearer sk-v9xxxx......" \
  -H "Content-Type: multipart/form-data" \
  -F file="@/root/audio.m4a" \
  -F model="whisper-1"

输出：{"text":"This is a test. Thank you!"}

如果改成经过openai_forward：
代码：
curl http://127.0.0.1:36001/v1/audio/translations \
  -H "Authorization: Bearer sk-v9xxxxx....." \
  -H "Content-Type: multipart/form-data" \
  -F file="@/root/audio.m4a" \
  -F model="whisper-1"

输出：
{
    "error": {
        "message": "We could not parse the JSON body of your request. (HINT: This likely means you aren't using your HTTP library correctly. The OpenAI API expects a JSON payload, but what was sent was not valid JSON. If you have trouble figuring out how to fix this, please contact us through our help center at help.openai.com.)",
        "type": "invalid_request_error",
        "param": null,
        "code": null
    }
}

输出日志：
nohup: ignoring input
╭─────────────────── 🤗 openai-forward is ready to serve!  ────────────────────╮
│  base-url                      route-prefix      api-key-polling-pool     no │
│  https://api.openai.com              /                  False                │
╰──────────────────────────────────────────────────────────────────────────────╯
INFO:     Started server process [3193]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:36001 (Press CTRL+C to quit)
INFO:     127.0.0.1:59014 - "POST /v1/audio/translations HTTP/1.1" 400 Bad Request

问题：不支持 /audio/translations 接口?
谢谢！

**Comment by beidongjiedeguang** [comment]
@tangyiyong 
感谢反馈，应该是请求头上的问题，我后面支持一下这块

**Comment by tangyiyong** [comment]
我i下载了，按照源码部署，出错。

部署步骤：
git clone https://github.com/beidongjiedeguang/openai-forward.git --depth=1
cd openai-forward

pip install -e .
openai-forward run 

出错信息：
# openai_forward run --port=36001

Traceback (most recent call last):
  File "/root/miniforge3/envs/work/bin/openai_forward", line 8, in <module>
    sys.exit(main())
  File "/home/wwwroot/default/books/services/proxy/openai-forward/openai_forward/__main__.py", line 72, in main
    fire.Fire(Cli)
  File "/root/miniforge3/envs/work/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/root/miniforge3/envs/work/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/root/miniforge3/envs/work/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/wwwroot/default/books/services/proxy/openai-forward/openai_forward/__main__.py", line 52, in run
    uvicorn.run(
  File "/root/miniforge3/envs/work/lib/python3.10/site-packages/uvicorn/main.py", line 429, in run
    config = Config(app, **kwargs)
TypeError: Config.__init__() got an unexpected keyword argument 'app_dir'

**Comment by beidongjiedeguang** [comment]
看上去是`uvicorn`的问题，你试着将它升级到最新版本

**Comment by tangyiyong** [comment]
升级 uvicorn 到最新版本之后可以了，谢谢！
