### ISSUE TITLE
请问docker一个进程能支持多少并发呀?

### ISSUE THREAD

**Issue by seetimee** [beidongjiedeguang/openai-forward#71]
服务器是2c2g的,需要开多个进程吗

**Comment by beidongjiedeguang** [comment]
Hi @seetimee ,
支持多大并发量确实是个重要的问题，但我暂时还没有做这个实验 :(  
- fastapi + uvicorn的性能还是过得去的，网络请求方面使用httpx库（它的异步性能低于aiohttp, 但一般情况下应是够用的）。
- 通常可以将workers设置为n ~ 2n+1之间(n是物理核心)，但由于整个服务都是异步的，可能workers设置超过n并不会带来性能提升。 单个进程空载时会占用约50MB的内存（但若设置了REQ_RATE_LIMIT会导致内存占用随用户数的升高而相应提升）

**Comment by gougui** [comment]
作者麻烦问下，现在大概支持多少key呀？我这加得比较多，运行不到1小时就大量超时了，前面是正常的。报错如下
| ERROR    | openai_forward.forwarding.base:try_send:112 - <class 'httpx.PoolTimeout'>:  traceback=Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/httpcore/_synchronization.py", line 125, in wait
    await self._anyio_event.wait()
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 1778, in wait
    if await self._event.wait():
  File "/usr/local/lib/python3.10/asyncio/locks.py", line 214, in wait
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/usr/local/lib/python3.10/site-packages/httpcore/_synchronization.py", line 124, in wait
    with anyio.fail_after(timeout):
  File "/usr/local/lib/python3.10/site-packages/anyio/_core/_tasks.py", line 119, in __exit__
    raise TimeoutError
TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 242, in handle_async_request
    raise exc
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 233, in handle_async_request
    connection = await status.wait_for_connection(timeout=timeout)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 35, in wait_for_connection
    await self._connection_acquired.wait(timeout=timeout)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_synchronization.py", line 123, in wait
    with map_exceptions(anyio_exc_map):
  File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.PoolTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/openai-forward/openai_forward/forwarding/base.py", line 88, in try_send
    return await self.client.send(req, stream=True)
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1617, in send
    response = await self._send_handling_auth(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 352, in handle_async_request
    with map_httpcore_exceptions():
  File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.PoolTimeout

**Comment by beidongjiedeguang** [comment]
@gougui 这个问题能否新开一个issue讨论？

**Comment by beidongjiedeguang** [comment]
@seetimee 
这里做了一个简单的性能测试：[benchmark](https://github.com/beidongjiedeguang/openai-forward/blob/main/Examples/benchmark/README.md)

**Comment by seetimee** [comment]
> @seetimee 
> 这里做了一个简单的性能测试：[benchmark](https://github.com/beidongjiedeguang/openai-forward/blob/main/Examples/benchmark/README.md)

感谢感谢
