### ISSUE TITLE
作者麻烦问下，现在大概支持多少key呀？我这加得比较多，运行不到1小时就大量超时了，前面是正常的。报错如下

### ISSUE THREAD

**Issue by gougui** [beidongjiedeguang/openai-forward#72]
作者麻烦问下，现在大概支持多少key呀？我这加得比较多，运行不到1小时就大量超时了，前面是正常的。报错如下
| ERROR    | openai_forward.forwarding.base:try_send:112 - <class 'httpx.PoolTimeout'>:  traceback=Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/httpcore/_synchronization.py", line 125, in wait
    await self._anyio_event.wait()
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 1778, in wait
    if await self._event.wait():
  File "/usr/local/lib/python3.10/asyncio/locks.py", line 214, in wait
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/usr/local/lib/python3.10/site-packages/httpcore/_synchronization.py", line 124, in wait
    with anyio.fail_after(timeout):
  File "/usr/local/lib/python3.10/site-packages/anyio/_core/_tasks.py", line 119, in __exit__
    raise TimeoutError
TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 242, in handle_async_request
    raise exc
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 233, in handle_async_request
    connection = await status.wait_for_connection(timeout=timeout)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 35, in wait_for_connection
    await self._connection_acquired.wait(timeout=timeout)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_synchronization.py", line 123, in wait
    with map_exceptions(anyio_exc_map):
  File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.PoolTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/openai-forward/openai_forward/forwarding/base.py", line 88, in try_send
    return await self.client.send(req, stream=True)
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1617, in send
    response = await self._send_handling_auth(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 352, in handle_async_request
    with map_httpcore_exceptions():
  File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.PoolTimeout

_Originally posted by @gougui in https://github.com/beidongjiedeguang/openai-forward/issues/71#issuecomment-1715471735_

**Comment by beidongjiedeguang** [comment]
Hi, @gougui ,
1. 代码中没有对`OPENAI_API_KEY`数量的限制，如果设置了它们会在请求时被逐个、依次、循环调用。 
2. 请问超时发生时会导致整个服务都不可用吗？还是只是特定的api-key超时，不影响其它请求？ 默认超时是300s，可以在环境变量中设置。另外，可以问下你的并发量和环境配置吗？

**Comment by gougui** [comment]
> Hi, @gougui ,
> 
> 1. 代码中没有对`OPENAI_API_KEY`数量的限制，如果设置了它们会在请求时被逐个、依次、循环调用。
> 2. 请问超时发生时会导致整个服务都不可用吗？还是只是特定的api-key超时，不影响其它请求？ 默认超时是300s，可以在环境变量中设置。另外，可以问下你的并发量和环境配置吗？

整个服务都不可用，全部超时，100个key正常，200以上运行段时间就会全部超时，感觉有点类似连接池满了又没释放导致后续请求全部超时。我用的docker一键启动，服务器资源充足。

**Comment by beidongjiedeguang** [comment]
比较奇怪，理论上使用多少个key对服务本身性能应该没有影响。听上去像是其中一个key的超时导致了整个服务崩溃。这个问题我后面关注一下，感谢反馈

**Comment by beidongjiedeguang** [comment]
我认为这个问题应该是openai的政策所致。现将该issue关闭，如果后续发现不是，可重新打开。
